services:
  postgres:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: instagram
      POSTGRES_USER: admin
    container_name: postgres
    restart: always